""".

Revision ID: 064116a29878
Revises: 
Create Date: 2025-06-06 14:44:22.427602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064116a29878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('folder_path')

    # ### end Alembic commands ###
